version: '3'
services:
  financial-advisor-nodejs:
    image: "hectorgomezv1/financial-advisor-nodejs:${FINANCIAL_ADVISOR_IMAGE_RELEASE}"
    container_name: financial-advisor-nodejs
    ports:
      - "5100:5100"
    environment:
      - FINANCIAL_ADVISOR_PROVIDER_BASE_URL=${FINANCIAL_ADVISOR_PROVIDER_BASE_URL}
      - FINANCIAL_ADVISOR_PROVIDER_API_TOKEN=${FINANCIAL_ADVISOR_PROVIDER_API_TOKEN}
      - FINANCIAL_ADVISOR_NEW_RELIC_APP_NAME=${FINANCIAL_ADVISOR_NEW_RELIC_APP_NAME}
      - FINANCIAL_ADVISOR_HTTP_SERVER_PORT=${FINANCIAL_ADVISOR_HTTP_SERVER_PORT}
      - FINANCIAL_ADVISOR_MONGO_CONNECTION_STRING=${FINANCIAL_ADVISOR_MONGO_CONNECTION_STRING}
      - FINANCIAL_ADVISOR_MONGO_DATABASE_NAME=${FINANCIAL_ADVISOR_MONGO_DATABASE_NAME}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
    links:
      - fa-mongo
    depends_on:
      - fa-mongo

  fa-auth-service:
    image: "hectorgomezv1/auth-service:${FA_ECHO_SERVER_IMAGE_RELEASE}"
    ports:
    - "4400:4400"
    links:
      - fa-mongo
    depends_on:
      - fa-mongo

  fa-echo-server:
    image: "hectorgomezv1/fa-echo-server:${FA_ECHO_SERVER_IMAGE_RELEASE}"
    container_name: fa-echo-server
    ports:
      - "4000:4000"
    environment:
      - NEW_RELIC_APP_NAME=${FA_ECHO_SERVER_NEW_RELIC_APP_NAME}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}

  fa-mongo:
    image: mongo:5-focal
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
