version: '3'
services:
  node-financial-advisor:
    image: "hectorgomezv1/node-financial-advisor:${FINANCIAL_ADVISOR_IMAGE_RELEASE}"
    container_name: node-financial-advisor
    ports:
      - "5100:5100"
    environment:
      - FINANCIAL_ADVISOR_PROVIDER_BASE_URL=${FINANCIAL_ADVISOR_PROVIDER_BASE_URL}
      - FINANCIAL_ADVISOR_PROVIDER_API_TOKEN=${FINANCIAL_ADVISOR_PROVIDER_API_TOKEN}
      - NEW_RELIC_APP_NAME=${FINANCIAL_ADVISOR_NEW_RELIC_APP_NAME}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - HTTP_SERVER_PORT=${HTTP_SERVER_PORT}
  node-fa-echo-server:
    image: "hectorgomezv1/fa-echo-server:${FA_ECHO_SERVER_IMAGE_RELEASE}"
    container_name: node-fa-echo-server
    ports:
      - "4000:4000"
    environment:
      - NEW_RELIC_APP_NAME=${FA_ECHO_SERVER_NEW_RELIC_APP_NAME}
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}